name: Artifacts
on:
  push:
    branch:
      - step4
  pull_request:
    branch:
      - step4
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check
        run: |
          ROW=`grep 'Hello' src/* -RHn`
          echo $ROW
          IFS=':' read -r -a list <<< "$ROW"
          echo $list[0]
          echo $list[1]
          echo "::error file=${list[0]},line=${list[1]}::No more Hello"
