name: Hello
on:
  push:
    branches:
      - step0

jobs:
  hellojob:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello world"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: File list
        run: |
          pwd
          ls -l
