name: Manual
on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'
        required: false
        default: ''

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Ok. ${{ github.event.inputs.comment }}"
